### ISSUE TITLE
Usage of romfs -> SD, not working?

### ISSUE THREAD

**Issue by mariohackandglitch** [44670/patchrom#1]
I succefully edited the code, and used it with HANS, however, there isn't any indications on how the romfs should be put on the SD.

Any hints?

**Comment by 44670** [comment]
I don't think it should be possible because the game have no access to sd card normally, you should patch exheader(hans could not do that) or run ntr cfw before launching the game.

**Comment by mariohackandglitch** [comment]
I used Mario Kart 7, which has access to SD ExtData, however, how should the romfs be put on the SD card?

**Comment by 44670** [comment]
it can not access to sd card directly with extdata premission .

**Comment by mariohackandglitch** [comment]
So let's say I patched the exheader, where is the romfs redirected to? can I change the redirected path?

**Comment by 44670** [comment]
nope, it is only possible to redirect to the root directory of sdcard.
it is recommended to use layeredfs plugin to do such redirection now: https://github.com/44670/layeredFS
